### PR TITLE
Reluvethel

### PR DESCRIPTION
**Pull request by Storm-Crow01**
Added the Daeroris faction; I'll work on the northern Faebalar faction over the next week.

### CODE REVIEW

**Comment by Hondolor** [comment]
Just tested it. Needs quite a bit of work before it can get pulled. More planets, and some fixes as well. One system had a ton of random space stations as well. Strange. Good progress though

**Comment by Storm-Crow01** [comment]
re: more planets needed- I've only done the planets for one of my two factions. The plan is to get this merged now, then i'll add the other faction in a second pull.
re: random space stations- That's the idea. c:

**Comment by Storm-Crow01** [comment]
There we go, the Faebalar have been added now.

**Comment by Hondolor** [comment]
Did you mean to leave all those satellites in the Merith system?

**Comment by Storm-Crow01** [comment]
Yes. As I said- it's intentional. (Those stations are meant to be where the Daeroris build their largest ships, thus why there's so many of them)

**Pull request merged**
